config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('users/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, ActivationSentView
from django.contrib.auth import views as auth_views

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activation_sent/', ActivationSentView.as_view(), name='activation_sent'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    phone = models.CharField(max_length=20, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=25, verbose_name='Страна', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django import forms

from users.models import User


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'country', 'first_name', 'last_name', 'phone', 'avatar')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

            self.fields["password"].widget = forms.HiddenInput()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, TemplateView

from users.forms import UserForm, UserRegisterForm
from users.models import User


class ProfileUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('catalog:product_list')


class ActivationSentView(TemplateView):
    template_name = 'users/activation_sent.html'

users/templates/users/activation_sent.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <h2>Регистрация</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <h2>Вход в личный кабинет</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn" value="Вход">
                    <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/password_reset_email.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}

                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <h2>Регистрация</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}