catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, \
    BlogDeleteView, ProductDetailView, ProductCreateView, ProductUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', cache_page(60 * 5)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_form'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_formset'),
    path('contacts/', contacts, name='index-contacts'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='block_form'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='block_form'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_confirm_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('users/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, ActivationSentView
from django.contrib.auth import views as auth_views

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activation_sent/', ActivationSentView.as_view(), name='activation_sent'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

catalog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model

NULLABLE = {'blank': True, 'null': True}

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.CharField(max_length=500, verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Product(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.CharField(max_length=500, verbose_name='Описание', **NULLABLE)
    image_preview = models.ImageField(upload_to='media/image/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Категория')
    purchase_price = models.IntegerField(verbose_name='Цена за покупку', **NULLABLE)
    creation_date = models.DateTimeField(verbose_name='Дата создания', **NULLABLE)
    last_modified_date = models.DateTimeField(verbose_name='Дата последнего изменения', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.description} {self.category}'

    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[str(self.pk)])

    def get_latest_version(self):
        active_version = self.version_set.filter(is_active=True).first()
        if active_version:
            return active_version
        else:
            return self.version_set.order_by('-version_number').first()

    def is_editable_by(self, user):
        return self.owner == user

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)


class Blog(models.Model):
    headline = models.CharField(max_length=50, verbose_name='Заголовок')
    slug = models.CharField(max_length=50, verbose_name='slug', **NULLABLE)
    content = models.TextField(max_length=1000, verbose_name='Содержание', **NULLABLE)
    preview = models.ImageField(upload_to='media/image/', verbose_name='Изображение', **NULLABLE)
    creation_date_blog = models.DateTimeField(verbose_name='Дата создания', **NULLABLE)
    publication_feature = models.CharField(max_length=50, verbose_name='Признак публикации', **NULLABLE)
    views_count = models.IntegerField(verbose_name='количество просмотров', default=0)

    def __str__(self):
        return f'{self.headline} {self.slug} {self.content} {self.publication_feature}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.headline)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блог'
        ordering = ('views_count',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.IntegerField(verbose_name='Номер версии', **NULLABLE)
    version_name = models.CharField(verbose_name='Название версии', max_length=255, **NULLABLE)
    is_active = models.BooleanField(verbose_name='Признак текущей версии', default=False, **NULLABLE)

    def __str__(self):
        return f"{self.product.name} - {self.version_number} - {self.version_name}"

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версия'

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models import Product, Blog, Version


class ProductVersion(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['product', 'version_number', 'version_name']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'purchase_price', 'image_preview']

    def clean_name(self):
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        name = self.cleaned_data['name'].lower()
        for word in forbidden_words:
            if word in name:
                raise ValidationError(f"Слово {word} не допускается в названии.")
        return name

    def clean_description(self):
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        description = self.cleaned_data['description'].lower()
        for word in forbidden_words:
            if word in description:
                raise ValidationError(f"Слово {word} не допускается в описании")
        return description


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['headline', 'content', 'preview', 'creation_date_blog']
        # fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page

from catalog.forms import ProductForm, BlogForm, ProductVersion
from catalog.models import Product, Blog, Version, Category
from django.core.cache import cache


class ProductListView(generic.ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.request.GET.get('category')

        if category_id:
            queryset = queryset.filter(category_id=category_id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def get_categories(self):
        categories = cache.get('categories')
        if categories is None:
            # Если данные отсутствуют в кеше, получаем их из базы данных
            categories = Category.objects.all()
            # Сохраняем данные в кеше на определенное время
            cache.set('categories', categories, timeout=3600)
        return categories


class ProductDetailView(generic.DetailView):
    model = Product

    @method_decorator(cache_page(60 * 5))  # Кеширование на 5 минут
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_form')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_formset.html'

    def get_success_url(self, *args, **kwargs):
        return reverse('catalog:product_formset', args=[self.get_object().pk])

    def dispatch(self, request, *args, **kwargs):
        if not self.get_object().is_editable_by(request.user):
            # Если пользователь не является владельцем продукта, перенаправляем на другую страницу или выводим ошибку
            return HttpResponseForbidden("Вы не являетесь владельцем данного продукта.")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(Product, Version, form=ProductVersion, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


########################################################################################################################
"""механизм CRUD для блога"""


class BlogListView(generic.ListView):
    model = Blog


class BlogDetailView(generic.DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        return context_data

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Увеличить количество просмотров на 1
        self.object.views_count += 1
        self.object.save()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = Blog
    # fields = ['headline', 'content', 'preview', 'creation_date_blog']
    form_class = BlogForm
    success_url = reverse_lazy('catalog:blog_list')


class BlogUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Blog
    form_class = BlogForm
    # fields = ['headline', 'content', 'preview', 'creation_date_blog']
    success_url = reverse_lazy('catalog:blog_list')


class BlogDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')


########################################################################################################################
"""Контактная информация"""


def contacts(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        massage = request.POST.get('massage')
        phone = request.POST.get('Phone')
        print(f'User_name: {name}, User_email: {email}, User_massage:{massage}, User_phone: {phone}')
    return render(request, 'catalog/index-contacts.html', )

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
    <link rel="icon" href="/static/images/favicon.ico">
    <link rel="shortcut icon" href="/static/images/favicon.ico"/>
    <link rel="stylesheet" href="/static/css/stuck.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/form.css">
    <link rel="stylesheet" href="/static/css/touchTouch.css">
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/jquery-migrate-1.1.1.js"></script>
    <script src="/static/js/script.js"></script>
    <script src="/static/js/superfish.js"></script>
    <script src="/static/js/jquery.equalheights.js"></script>
    <script src="/static/js/jquery.mobilemenu.js"></script>
    <script src="/static/js/jquery.easing.1.3.js"></script>
    <script src="/static/js/tmStickUp.js"></script>
    <script src="/static/js/jquery.ui.totop.js"></script>
    <script src="/static/js/touchTouch.jquery.js"></script>
    <script src="/static/js/TMForm.js"></script>
    <script src="/static/js/modal.js"></script>


    <script>
 $(document).ready(function(){

  $().UItoTop({ easingType: 'easeOutQuart' });
  $('#stuck_container').tmStickUp({});
  $('.gallery .gall_item').touchTouch();

  });

    </script>
    <style>
    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .row .col-md-3 {
        flex-basis: 23%;
        margin-bottom: 20px;
    }

    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .row .col-md-3 {
        flex-basis: 23%;
        margin-bottom: 20px;
    }

    .buy-button {
        margin-top: 10px;
        text-align: center;
    }

    .black-border-button {
        display: inline-block;
        padding: 10px 20px;
        border: 2px solid #000;
        color: #000;
        text-decoration: none;
    }






    </style>

    <!--[if lt IE 9]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
            <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0"
                 height="42" width="820"
                 alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."/>
        </a>
    </div>
    <script src="/static/js/html5shiv.js"></script>
    <link rel="stylesheet" media="screen" href="/static/css/ie.css">


    <![endif]-->
</head>

<body class="page1" id="top">
<!--==============================
              header
=================================-->
<header>
    <!--==============================
                Stuck menu
    =================================-->
    <section id="stuck_container">
        <div class="container">
            <div class="row">
                <div class="grid_12">
                    <h1>
                        <a href="#">
                            <img src="/static/images/logo.png" alt="Logo alt">
                        </a>
                    </h1>
                    <div class="navigation">
                        <nav>
                            <ul class="sf-menu">
                                <li class="current"><a href="/">Главная</a></li>
                                <li><a href="{% url 'catalog:blog_list' %}">Блог</a></li>
                                <li><a href="{% url 'catalog:index-contacts' %}">Контакты</a></li>
                                <li><a href="{% url 'catalog:block_form' %}">Создать статью</a></li>
                                <li><a href="{% url 'catalog:product_form' %}">Добавить продукт</a></li>
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'users:profile' %}">Профиль</a></li>
                                <li><a href="{% url 'users:logout' %}">Выход</a></li>
                                {% else %}
                                <li><a href="{% url 'users:login' %}">Вход</a></li>
                                <li><a href="{% url 'users:register' %}">Регистрация</a></li>
                                {% endif %}

                            </ul>
                        </nav>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</header>
{% block content %}
{% endblock %}
<!--==============================
              footer
=================================-->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <div class="socials">
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-google-plus"></a>
                    <a href="#" class="fa fa-pinterest"></a>
                </div>
                <div class="copyright"><span class="brand">Bliss </span> &copy; <span id="copyright-year"></span> | <a
                        href="#">Privacy Policy</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<a href="#" id="toTop" style="margin-right: -63px; right: 50%; display: block;"><span id="toTopHover"></span></a>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <h2>Написать статю</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                      Вы уверены, что хотите удалить статью?
                    <input type="submit" class="btn" value="Уверен">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_7">
                <div class="blog">
                    <div class="blog_title"><a href="{% url 'catalog:blog_list' object.pk %}">{{ object.headline }}</a>
                    </div>
                    {% if object.preview %}
                    <a href="{{ object.get_absolute_url }}"><img src="{{ object.preview.url }}"
                                                                 alt="{{ object.headline }}" width="800"
                                                                 height="400"></a>
                    {% endif %}
                    <p>{{ object.content }}</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <h2>Написать статю</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="reset" class="btn" value="Очистить">
                    <input type="submit" class="btn" value="{% if object %}Сохранить{% else %}Создать{% endif%}">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<!--=====================
          Content
======================-->
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h2>Блог</h2>
            </div>
            {% for object in object_list %}
            <div class="blog">
                <div class="blog_title"><a href="{% url 'catalog:blog_list' object.pk %}">{{ object.headline }}</a>
                </div>
                {% if object.preview %}
                <a href="{{ object.get_absolute_url }}"><img src="{{ object.preview.url }}"
                                                             alt="{{ object.headline }}" width="800"
                                                             height="400"></a>
                {% endif %}
                <p>{{ object.slug }}</p>
                <p>{{ object.content }}</p>
                <table>
                    <tbody>
                    <tr>
                        <td>
                            <time datetime="2014-01-01">
                                <span class="fa fa-calendar"></span>
                                {{ object.creation_date_blog}}
                            </time>
                        </td>
                        <td><a href="#">
                            <div class="fa fa-user"></div>
                            Admin</a></td>
                        <td><a href="#"><span class="fa fa-link"></span> Permalink</a></td>
                    </tr>
                    <tr>
                        <td>
                            <div class="fa fa-bookmark"></div>
                            Uncategorized
                        </td>
                        <td colspan="2">
                            <div class="fa fa-tag"></div>
                            No tags
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="fa fa-comments"></div>
                            No comments
                        </td>
                        <td colspan="2">
                            <div class="fa fa-eye"></div>
                            {{ object.views_count }}
                            <div class="fa fa-thumbs-up"></div>
                            0
                            <div class="fa fa-thumbs-down"></div>
                            0
                        </td>
                    </tr>
                    </tbody>
                </table>
                <a href="{% url 'catalog:block_form' object.pk %}" class="btn" role="button">Изменить</a>
                <a href="{% url 'catalog:blog_confirm_delete' object.pk %}" class="btn" role="button">Удалить</a>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/index-contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<!--=====================
          Content
======================-->
<section class="content ctn__1">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h2>Как нас найти</h2>
                <div class="map">
                    <div class="row">
                        <div class="grid_9">
                            <figure class="">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d24214.807650104907!2d-73.94846048422478!3d40.65521573400813!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1395650655094"
                                        style="border:0"></iframe>
                            </figure>
                        </div>
                        <div class="grid_3">
                            <div class="map_block">
                                <div class="map_title">Адрес:</div>
                                Минск, Пр-т Партизанский 102. <br> Могилев, ул. Строителей 10А.
                            </div>
                            <div class="map_block">
                                <div class="map_title">Phones:</div>
                                +375 29 800 59 65 <br>+375 33 800 60 60
                            </div>
                            <div class="map_block">
                                <div class="map_title">Email:</div>
                                <a href="#">bliss@demolink.org</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid_8">
                <p>24/7 support is on for all <span class="color1 fw"><a href="http://www.templatemonster.com/"
                                                                         rel="nofollow">premium themes</a></span>. <br>
            </div>
        </div>
    </div>
</section>
{% endblock%}

catalog/templates/catalog/index-home.html
{% extends 'catalog/base.html' %}
{% block content %}
<!--=====================
          Content
======================-->
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h2>Продукты</h2>
            </div>

            {% for object in object_list %}
            <div class="col-md-3">
                <div class="single-products">
                    <div class="product-image">
                        <a href="{{ object.get_absolute_url }}"><img src="{{ object.image_preview.url }}"
                                                                     alt="{{ object.name }}" width="370"
                                                                     height="270"></a>
                        <div class="block2">
                            <time datetime="2014-01-01">{{object.purchase_price}}<br>Руб.</time>
                            <div class="extra_wrapper">
                                <div class="text1"><a href="#">{{ object.name }}</a></div>
                                {{object.description}}
                            </div>
                        </div>
                    </div>
                    <div class="buy-button">
                        <a href="#" class="black-border-button">Купить</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_7">
                <div class="product">
                    <div class="product_title"><a href="{% url 'catalog:product_detail' object.pk %}">{{ object.name }}</a>
                    </div>
                    {% if object.image_preview %}
                    <a href="{{ object.get_absolute_url }}"><img src="{{ object.image_preview.url }}"
                                                                 alt="{{ object.name }}" width="800"
                                                                 height="400"></a>
                    {% endif %}
                    <p>{{ object.description }}</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="content">
    <div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
    <div class="container">
        <div class="row">
            <div class="grid_11">
                <h2>Добавьте продукт</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="reset" class="btn" value="Очистить">
                    <input type="submit" class="btn" value="{% if object %}Сохранить{% else %}Создать{% endif%}">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="content">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h2>Категории</h2>
            </div>
            <div class="col-md-12">
                <form id="category-filter-form" method="get">
                    <select name="category">
                        <option value="">Все категории</option>
                        {% for category in categories %}
                        <option value="{{ category.pk }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit">Фильтр</button>
                </form>
            </div>
        </div>
        <div class="row">
            {% for object in object_list %}
            <div class="col-md-3">
                <div class="single-products">
                    <div class="product-image">
                        <a href="{{ object.get_absolute_url }}">
                            <img src="{{ object.image_preview.url }}" alt="{{ object.name }}" width="370" height="270">
                        </a>
                    </div>
                    <div class="product-info">
                        <div class="block2 mb-2">
                            <time datetime="2014-01-01">{{ object.purchase_price }}<br>Руб.</time>
                            <div class="extra_wrapper">
                                <div class="text1"><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></div>
                            </div>
                        </div>
                        <div class="buy-button">
                            <a href="#" class="black-border-button">Купить</a>
                            <a href="{% url 'catalog:product_formset' object.pk %}"
                               class="black-border-button">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<style>
    .product-image {
        margin-bottom: 2rem; /* Измените значение здесь по вашему усмотрению */
    }

</style>

{% endblock %}